ajout de Jacoco.xml pour lire le testCoverage sur CodeCov v5

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,8 +19,15 @@ jobs:
           name: Generate Coverage Report
           command: mvn jacoco:report
       - run:
-          name: Generate Aggregated Coverage Report
-          command: mvn jacoco:report-aggregate
+          name: Check for Jacoco Report File
+          command: |
+            if [ -f target/jacoco/jacoco.xml ]; then
+              echo "Jacoco report found!"
+              cat target/jacoco/jacoco.xml | head -n 20
+            else
+              echo "Jacoco report not found in target/jacoco/"
+              exit 1
+            fi
 
 
   upload-codecov:
